// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocgblrlfvmngvvuneybh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jZ2Jscmxmdm1uZ3Z2dW5leWJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5NjMzMjYsImV4cCI6MjA1NDUzOTMyNn0.464bd2Efe8qoIcAa0dBunxJWdJfSexRzzxeBN7nP_-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);